--ricette--
INSERT INTO ricette (number_of_portions, preparation_time, image, ingredients, title, recipe_text) VALUES( 6, 80, 'https://i.pinimg.com/564x/f0/f0/c1/f0f0c141ab61f44eabfa5af701dad27e.jpg', '600 g di pane vecchio, 600 ml di latte, 2 fette spesse di salame all aglio, 3 uova, 2 etti di formaggio Vezzena stagionato, prezzemolo tritato, brodo vegetale, sale, qualche cucchiaio di farina', 'Canederli trentini', 'Cominciate dal brodo vegetale. In una pentola unite 1 patata, 1 cipolla, 2 spicchi di aglio, gambi di sedano, prezzemolo, carote, una zucchina e una crosta di formaggio, sale e pepe. Cuocere per circa 1 ora. Fate delle grandi briciole di pane. Scaldate il latte e unitelo al pane, amalgamatelo. Tagliate il salame a tocchetti. Quando l impasto si sarà raffreddato unite le uova, il prezzemolo tritato, il formaggio grattugiato, il salame e salate. Lasciar riposare l impasto in frigo per 24 ore. A questo punto, mettete qualche cucchiaio di farina in un piatto. Formate delle palline. Passateli nella farina. Scaldate il brodo e calatevi i canederli. Fateli cuocere per 10 - 15 minuti. Servite');
INSERT INTO ricette (number_of_portions, preparation_time, image, ingredients, title, recipe_text) VALUES(8, 30, 'https://i.pinimg.com/564x/44/8a/17/448a179b6d41ee5393187430c7ae611d.jpg', '250 g di biscotti tipo digestive, 125 g di burro, 750 g di formaggio fresco tipo Philadelphia, 170 ml di panna fresca, 80 g di zucchero semolato, 1/2 bacca di vaniglia, 250 g di confettura di lamponi, succo di limone', 'Cheeskcake fredda', 'Iniziate la preparazione dalla base: tritate i biscotti, metteteli in una ciotola e amalgamateli con il burro fuso. Ricoprite il fondo di uno stampo da 22 cm di diametro. Ponete in frigorifero fino al momento di comporre il dolce. Mettete in ammollo la gelatina in acqua. In una ciotola montate il formaggio e lo zucchero, 150 g di panna e i semi di vaniglia estratti dalla bacca, fino a ottenere un composto omogeneo. Ponete la panna restante in una casseruola e fatela scaldare. Unitevi la gelatina strizzata e mescolate, fatela sciogliere. Fate raffreddare e aggiungete il miscuglio al composto di formaggio fresco, amalgamando bene. Versate il tutto sulla base di biscotti, livellate e ponete in frigorifero per almeno 4 ore. Dopo scaldate la marmellatacon acqua e succo di limone. Lasciatela intiepidire e distribuitela sul dolce. Ponete nuovamente in frigorifero per 1 ora.');
INSERT INTO ricette (number_of_portions, preparation_time, image, ingredients, title, recipe_text) VALUES(7, 40, 'https://i.pinimg.com/564x/a0/e1/c6/a0e1c660f37c106926f2666a175aa944.jpg', '3 fette di pane raffermo, 1/2 bicchiere di latte, 800 g di carne di manzo tritata, 4 cucchiai di parmigiano, 300 g di polpa di pomodoro, 1/2 cucchiaio di concentrato di pomodoro, 3 cucchiai di olio evo, sale', 'Polpette al sugo', 'Private le fette di pane della crosta, spezzettatele e fatele ammorbidire in una ciotola con il latte. Lasciatele riposare e poi schiacciatele con una forchetta. In caso ci fosse del latte in eccesso, strizzate la mollica ed eliminatelo. Unite al pane la carne trita, il parmigiano ed aggiustate di sale. Impastate bene con le mani fino a ottenere un composto omogeneo. Prendete il composto e formate con le mani delle polpette rotonde della grandezza di un uovo. Scaldate l olio in una padella e fatevi rosolare le polpette da tutti i lati per un paio di minuti; aggiungete la polpa di pomodoro con il concentrato e una presa di sale. Mescolate bene, coprite e fate cuocere per 20-25 minuti a fuoco dolce. Verso metà cottura giratele in modo che cuociano uniformemente e senza attaccare.');
INSERT INTO ricette (number_of_portions, preparation_time, image, ingredients, title, recipe_text) VALUES(2, 70, 'https://i.pinimg.com/564x/1b/ce/95/1bce959dd250f841fbb882b099b66ea6.jpg', '3 melanzane, 4 cucchiai di tahina, 2 spicchi di aglio, 1 limone, 1 cucchiaio di olio evo, 1 cucchiaino di sale, paprika','Babaganoush', 'Per preparare il babaganoush raccogliete gli ingredienti e iniziate a cuocere le melanzane. Lavatele e asciugatele, incidetele nel senso della lunghezza, avvolgetele in un cartoccio di alluminio per alimenti e mettetele in forno caldo a 220° per un ora circa. Nel frattempo schiacciate l’aglio e spremete il limone. Uniteli in una ciotola capiente e aggiungete la tahina, mescolando bene il composto in modo da renderlo liscio. Quando le melanzane sono cotte, lasciatele raffreddare, poi sbucciatele con un coltellino affilato e raccoglietene la polpa con l aiuto di un cucchiaio. Scartate la buccia. Aggiungete la polpa di melanzane nella ciotola con l aglio, il limone e la tahina, quindi schiacciate il tutto con l aiuto di uno schiacciapatate a disco forato o con una forchetta, mescolando in modo da amalgamare al meglio tutti gli ingredienti. Il babaganoush non deve essere una crema liscia: quella che si deve ottenere è una consistenza cremosa ma non uniforme e totalmente "frullata". Aggiustate la consistenza e il sapore della crema unendo olio e sale.');

--categorie--
INSERT INTO categoria (name) VALUES('primi');
INSERT INTO categoria (name) VALUES('secondi');
INSERT INTO categoria (name) VALUES('contorni');
INSERT INTO categoria (name) VALUES('dolci');